#ifndef BUTTERWORTHFILTER_GLOBAL_H
#define BUTTERWORTHFILTER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BUTTERWORTHFILTER_LIBRARY)
#  define BUTTERWORTHFILTERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BUTTERWORTHFILTERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif
